### ISSUE TITLE
help request: kubernetes and haproxy formula

### ISSUE THREAD

**Issue by slimakcz** [salt-formulas/salt-formula-kubernetes#10]
Hi,
I would like to use haproxy ssl termination for kubernets API.
I have issue with ssl cert. My reclass for haproxy:
```
 haproxy:
    proxy:
      listen:
        k8s_secure:
          type: http
          options:
            - ssl-hello-chk
          binds:
          - address: ${_param:cluster_vip_address}
            port: 443
            ssl:
              enabled: true
              pem_file: /etc/kubernetes/ssl/kubernetes-server.pem
```
but if I first run salt-call state.apply haproxy, then this state failed, because I don't have prepared pem file.
So, I tried to first run: salt-call state.sls kubernetes exclude=kubernetes.master.setup, but this fails too, because:
```
/etc/kubernetes/ssl/{{ filename }}:
  file.managed:
    - source: salt://{{ master.get('cert_source','_certs/kubernetes') }}/{{ filename }}
    - user: root
    {%- if pillar.get('haproxy', {}).get('proxy', {}).get('enabled') %}
    - group: haproxy
    {%- else %}
    - group: root
    {%- endif %}
    - mode: 640
    - watch_in:
      - service: master_services
```
for create certificate you need haproxy group first. And this group is prepared by haproxy formula.

Please, could you help my way how to use both formula in one time?
